FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY lib/db/package.json ./lib/db/
COPY tsconfig.base.json tsconfig.json ./
RUN pnpm install --frozen-lockfile --filter @workspace/db

COPY lib/db ./lib/db

RUN pnpm --filter @workspace/db run build

CMD ["node", "-e", "require('./lib/db/dist/migrate.js')"]
