FROM node:22-bookworm-slim AS base
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml* ./
COPY lib/db/package.json ./lib/db/
COPY tsconfig.base.json tsconfig.json ./
RUN pnpm install --filter @workspace/db

COPY lib/db ./lib/db

CMD ["pnpm", "--filter", "@workspace/db", "run", "push"]
