import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import plansRouter from "./plans";
import creditsRouter from "./credits";
import statsRouter from "./stats";
import generateRouter from "./generate";
import templatesRouter from "./templates";
import botRouter from "./bot";
import sitesRouter from "./sites";
import articlesRouter from "./articles";
import pipelineRouter from "./pipeline";
import logsRouter from "./logs";
import settingsRouter from "./settings";
import adminRouter from "./admin";
import historyRouter from "./history";
import subscriptionRouter from "./subscription";
import keysRouter from "./keys";
import systemTemplatesRouter, { adminSystemTemplatesRouter } from "./system-templates";
import testRouter from "./test";
import photoRouter from "./photo";
import billingRouter from "./billing";
import paymentsUserRouter from "./payments_user";
import publicRouter from "./public";
import rssRouter from "./rss";
import blogSettingsRouter from "./blog-settings";
import nanobananaRouter from "./nanobanana/index";
import pointsRouter from "./points";
import v1Router from "./v1";
import savedDesignsRouter from "./saved-designs";
import aiBackgroundRouter from "./ai-background";
import addonsRouter from "./addons";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/plans", plansRouter);
router.use("/subscription", subscriptionRouter);
router.use("/credits", creditsRouter);
router.use("/stats", statsRouter);
router.use("/generate", generateRouter);
router.use("/history", historyRouter);
router.use("/keys", keysRouter);
router.use("/templates", templatesRouter);
router.use("/bot", botRouter);
router.use("/sites", sitesRouter);
router.use("/articles", articlesRouter);
router.use("/pipeline", pipelineRouter);
router.use("/logs", logsRouter);
router.use("/settings", settingsRouter);
router.use("/admin", adminRouter);
router.use("/system-templates", systemTemplatesRouter);
router.use("/admin/system-templates", adminSystemTemplatesRouter);
router.use("/test", testRouter);
router.use("/photo", photoRouter);
router.use("/billing", billingRouter);
router.use("/payments", paymentsUserRouter);
router.use("/public", publicRouter);
router.use("/rss", rssRouter);
router.use("/rss-feeds", rssRouter);
router.use("/blog-settings", blogSettingsRouter);
router.use("/nanobanana", nanobananaRouter);
router.use("/points", pointsRouter);
router.use("/v1", v1Router);
router.use("/saved-designs", savedDesignsRouter);
router.use("/designs", savedDesignsRouter);
router.use("/ai-background", aiBackgroundRouter);
router.use("/addons", addonsRouter);

export default router;
